
["MUTANT JUNGLE ZOMBIE ARM"]
	"Grab Durability Consumption (default: 1)" = 1
	"Strangle Damage (default: 2)" = 2.0
	"Grab Cooldown (in ticks, default: 200)" = 200
	"Max Grab Duration (in ticks, default: 200)" = 200
	"Durability (default: 200)" = 200
	"Attack Range Increase (default: 2)" = 2.0

[LEAFBLOWER]
	"Use Durability Consumption (default: 1)" = 1
	"Poison Damage (default: 1)" = 1.0
	"Suck Cooldown (in ticks, default: 20)" = 20
	"Blow Cooldown (in ticks, default: 200)" = 200
	"Max Use Duration (in ticks, default: 200)" = 200
	"Durability (default: 200)" = 200
	"Shoot Range (in blocks, default: 15)" = 15

["SENTRY VINE"]
	"Attack Damage (default: 6)" = 6.0
	"Attack Poison Effect Duration (in ticks, default: 100)" = 100
	"Attack Poison Effect Level (default: 1)" = 1
	"Attack Cooldown (in ticks, default: 5)" = 5
	"Slam Damage (default: 10)" = 10.0
	"Slam Cooldown (in ticks, default: 100)" = 100
	"Locked Horizontal Movement (default: true)" = true
	"Max Health (default: 100)" = 100.0
	"Fed Heal Amount (in percent, default: 10)" = 10
	"Knockback Resistance (default: 1)" = 1.0
	"Armour Value (default: 0)" = 0.0
	"Armour Toughness (default: 0)" = 0.0
	"Target Mobs Range (in blocks, default: 15)" = 15.0
	"Friendly Fire (default: false)" = false
	"Attacks Ignore Hurt Invulnerability (default: true)" = true

