"Retexture Hearts When Heated (default: true)" = true
"Pure Orange Heat Overlay (default: false)" = false
"Static Flame Heat Overlay (default: false)" = false
"Animated Flame Heat Overlay (default: true)" = true
"Orange Edges Heat Overlay (default: false)" = false
"Ash Heat Overlay (default: true)" = true

