ItemEvents.tooltip((event) => {
    event.add("divinerpg:ice_shards", Text.of(["击杀冰晶雪原维度里面的所有怪物时都会掉落\n", "使用雪块和雪景球可以搭建去往该维度的传送门"]).blue())
    event.add("enigmaticlegacy:the_cube", Text.of(["此物品不可合成：", "因为已经被林芝删掉了"]).blue())
    event.add("iter_rpg:earth_fragment", Text.of("你需要合成一个大地元素刷怪蛋以获取该物品\n或者找到大地神殿(Earth Shrine)，将中间的【Earth Seal】方块破坏掉\n之后就能自然生成大地元素").green())
    event.add("iter_rpg:water_fragment", Text.of("你需要合成一个水元素刷怪蛋以获取该物品\n或者找到水神殿(Water Shrine)，将中间的【Water Seal】方块破坏掉\n之后就能自然生成水元素").blue())
    event.add("iter_rpg:air_fragment", Text.of("你需要合成一个空气元素刷怪蛋以获取该物品\n或者找到空气神殿(Air Shrine)，将中间的【Air Seal】方块破坏掉\n之后就能自然生成空气元素").white())
    event.add("iter_rpg:fire_fragment", Text.of("你需要合成一个火元素刷怪蛋以获取该物品\n或者找到火神殿(Fire Shrine)，将中间的【Fire Seal】方块破坏掉\n之后就能自然生成火元素").red())
    event.add("iter_rpg:void_fragment", Text.of("你需要合成一个虚空元素刷怪蛋以获取该物品\n或者找到虚空神殿(Void Shrine)，将中间的【Void Seal】方块破坏掉\n之后就能自然生成虚空元素").lightPurple())
    event.add("iter_rpg:bottle_of_obsidian_tears", Text.of("获取该物品需要泪滴捕捉器").lightPurple())
    event.add("iter_rpg:tear_catcher", Text.of(["只需要将哭泣的黑曜石放置在上面\n", "一段时间后用玻璃瓶即可收集泪滴\n", "不要看上面白色的话，你要相信林芝"]).lightPurple())
    event.add("spartanweaponry:simple_handle", Text.of("你知道吗，树枝其实就是木棍").green())
    event.add("infinite_abyss:astarium_crystal", Text.of("获取它需要使用紫钻石钻头挖取魔能矿石，一般在第六层中存在").white())
    event.add("infinite_abyss:vicerite_crystal", Text.of("获取它需要使用紫钻石镐挖取渍恶水晶矿石\n一般在第五层的上方天花板或地下").white())
    event.add("savage_and_ravage:wand_of_freezing",Text.of("手持时，玩家自身攻击伤害 +55").white())
    event.add("goety:dark_scythe",Text.of("手持时，玩家自身攻击伤害 +60").white())
    event.add("goety:dark_metal_scythe",Text.of("手持时，玩家自身攻击伤害 +64").white())
    event.add("goety:death_scythe",Text.of("手持时，玩家自身攻击伤害 +72").white())
    event.add("cataclysm:ceraunus",Text.of("手持时，玩家自身攻击伤害 +100").white())
    event.add("cataclysm:the_incinerator",Text.of("手持时，玩家自身攻击伤害 +121").white())
    event.add("cataclysm:soul_render",Text.of("手持时，玩家自身攻击伤害 +144").white())
    event.add("bedrock_edition_features:element_constructor", Text.of(["想要查看创建某个妙妙元素的说明吗?\n", "请用鼠标对准我按下B键"]).yellow())  
    event.add("bedrock_edition_features:compoundcreator", Text.of(["想要查看创建某个化合物的说明吗?\n", "请用鼠标对准我按下B键"]).yellow()) 
    event.add("bedrock_edition_features:labtable", Text.of(["想查看创建某化学物品的说明吗?\n", "请用鼠标对准我按下B键"]).yellow())
    event.add("infinite_abyss:seventh_layer_deepstone", Text.of("挖掘它需要使用紫钻石镐").lightPurple())
    event.add("minecraft:snowball", Text.of("三分之一的概率可以生成冰结球").blue())
    event.add("linzhi:difficulty_reset_button", Text.of("第一章前可用").yellow())
    event.add("divinerpg:oxdrite_ingot", Text.of("在冰原维度中击败冰冻血肉即可获取该物品").yellow())
    event.add("infinite_abyss:summoning_bell", Text.of("可以在第四层菌落维度中用以生成查莉亚boss").yellow())
    event.add("infinite_abyss:fourth_layer_deepstone", Text.of("在第四层菌落维度中获取").yellow())
    event.add("divinerpg:rupee_ingot", Text.of("可通过击杀溺尸获得").yellow())
    event.add("divinerpg:arlemite_ingot", Text.of("可通过击杀苦力怕获得").yellow())
    event.add("infinite_abyss:deepstone", Text.of("在第一层中可以挖掘得到").yellow())
    event.add("infinite_abyss:crystal_heart", Text.of("可以在第一层召唤boss").yellow())
    event.add("infinite_abyss:deepsilver_ore", Text.of("一般在第四层的水中常见").yellow())
    event.add("infinite_abyss:deepsilver_plate", Text.of("它的矿物一般在第四层的水中常见，需要用紫钻石镐挖掘").yellow())
    event.add("divinerpg:torridite_ingot", Text.of("在地狱中有").yellow())
    event.add("infinite_abyss:sixth_layer", Text.of("击杀第五层中的沉沦守卫即可获得").yellow())
    event.add("infinite_abyss:seventh_layer", Text.of("击杀第六层中的风灵即可获得").yellow())
    event.add("l2complements:captured_wind", Text.of("在高空中使用拔刀剑的下劈容易获取该物品").yellow())
    event.add("endrem:cryptic_eye", Text.of("可以自行合成").yellow())
    event.add("endrem:cursed_eye", Text.of("可以自行合成").yellow())
    event.add("endrem:black_eye", Text.of("可以自行合成").yellow())
    event.add("endrem:magical_eye", Text.of("可以自行合成").yellow())
    event.add("endrem:evil_eye", Text.of("可以自行合成").yellow())
    event.add("minecraft:crafting_table", Text.of("工作台配方已被修改，请在EMI中查看").yellow())
    event.add("farmersdelight:rice", Text.of("需要种在一格水的耕地中").yellow())
    event.add("minecraft:grindstone", Text.of(" 在砂轮用书驱魔的时候不要按shift，不然你的装备会爆掉！").yellow())
    event.add("botania:mana_diamond", Text.of("将钻石扔进魔力池中获得").yellow())
    event.add("iter_rpg:flawless_diamond", Text.of("需要在锻造台中合成").yellow())
    event.add("create:cardboard", Text.of("在动力冲压机中使用纸浆压制可得").yellow())
    event.add("botania:lexicon", Text.of("请阅读和学习【基础知识】【使用魔力】【产能类植物】三个部分\n如果你本来就有基础，那就不需要看这么多\n模组中的物品配方以EMI观察为准").yellow())
    event.add("ars_nouveau:worn_notebook", Text.of("请阅读和学习【入门指南】\n如果你本来就有基础，那就不需要看这么多\n模组中的物品配方以EMI观察为准").yellow())
    event.add("farmersdelight:roast_chicken", Text.of("先制作烤鸡，之后用碗右键烤鸡即可获得").yellow())
    event.add("infinite_abyss:glowing_green_crystal_block", Text.of("在第一层中可以挖掘得到").yellow())
    event.add("infinite_abyss:glowing_pink_crystal", Text.of("在第一层中可以挖掘得到").yellow())
    event.add("infinite_abyss:pink_glowing_crystal", Text.of("在第一层中可以挖掘得到").yellow())
    event.add("infinite_abyss:deeprock_golem_spirit_stone", Text.of("击杀第二层的奴隶傀儡可得").yellow())
    event.add("infinite_abyss:fire_crystal", Text.of("可在第二层中挖掘得到").yellow())
    event.add("infinite_abyss:glowing_red_crystal", Text.of("可在第二层中挖掘得到").yellow())
    event.add("divinerpg:purple_blaze", Text.of("击杀灵魂沙三角洲中的紫焰人时概率掉落，也可以自行制作").yellow())
    event.add("goety:dark_wand", Text.of("配方所需的缠魂木板可以自己自行制作【缠魂树苗】，生长后砍下获得").yellow())
    event.add("undergarden:twistytwig", Text.of("摇蜿木可以在摇蜿森林和茂密森林群系中被找到").yellow())
    event.add("undergarden:rotten_blisterberry", Text.of("收取疱莓丛时概率掉落").yellow())
    event.add("apotheosis:rare_material", Text.of("使用回收台分解词缀物品可获得珍宝材料").yellow())
    event.add("infinite_abyss:violet_diamond", Text.of("可由无暇钻石烧炼或者在第二层中挖掘得到").yellow())
    event.add("infinite_abyss:opal", Text.of("可在第二层中挖掘得到").yellow())
    event.add("infinite_abyss:cursed_opal", Text.of("可在第四层中挖掘得到").yellow())
    event.add("divinerpg:aquatic_pellets", Text.of("击杀多管水母或帝王蟹可以得到").yellow())
    event.add("divinerpg:aqua_ball", Text.of("多管水母的掉落物也有这个，或者自己制作也行").yellow())
    event.add("divinerpg:soulfire_stone", Text.of("怒焰王的掉落物").yellow())
    event.add("iceandfire:frost_lily", Text.of("在雪地平原上生成，一般生成在原版冰方块上面").yellow())
    event.add("divinerpg:molten_shards", Text.of("击杀地狱芝蛛或野火弓箭手获得").yellow())
    event.add("infinite_abyss:layer_2_stalagmite", Text.of("在第二层中可以挖掘得到").yellow())
    event.add("minecraft:totem_of_undying", Text.of("击杀唤魔者或者腐衰凶兽可以获得").yellow())
    event.add("undergarden:regalium_crystal", Text.of("在深暗之园中可以挖掘得到").yellow())
    event.add("iter_rpg:etherbloom", Text.of("通过与流浪商人交易获得，也会极少量的自然生成在草甸、森林和平原中\n获得一次之后可以分解为以太花种子，种植在紫黄晶块或紫水晶块上").yellow())
    event.add("farmersdelight:rich_soil", Text.of("将有机肥料放置于世界中，一段时间后有机肥料将会自然降解为沃土\n有机肥料的降解在日光下和在水附近会被加速\n还可以放置催化物来加速分解\n默认有以下几种催化物：\n棕色蘑菇、红色蘑菇\n棕色蘑菇菌落、红色蘑菇菌落\n灰化土、菌丝等等").yellow())
    event.add("divinerpg:terran_shards", Text.of("击杀科布林获得").yellow())
    event.add("divinerpg:divine_shards", Text.of("击杀监视者可以获得").yellow())
    event.add("iter_rpg:sacred_twig", Text.of("神圣树生长成的神圣树叶自然掉落低概率可获得\n神圣树苗会自然生成在 Air Shrine（在天上） 之中\n也会极少量地生成在桦木树林、繁花森林和黑森林之中").yellow())
    event.add("iter_rpg:sanguarnet", Text.of("它的矿石生成在任意维度 Y=-64 至 Y=0 之间").yellow())
    event.add("bedrock_edition_features:elixir", Text.of("在酿造台中往粗制的药水加入钴即可获得").yellow())
    event.add("divinerpg:eden_heart", Text.of("杀死太阳风暴可得").yellow())
    event.add("minecraft:jigsaw", Text.of("活过炼狱游者的第二阶段即可获得").yellow())
    event.add("deeperdarker:sculk_bone", Text.of("击杀幽匿维度中的破碎者或幽匿蜈蚣可获得").yellow())
    event.add("deeperdarker:soul_crystal", Text.of("击杀幽匿维度的追猎者可获得").yellow())
    event.add("deeperdarker:soul_dust", Text.of("击杀幽匿维度中的幽匿水蛭可获得").yellow())
    event.add("mutantmonsters:endersoul_hand", Text.of("首先你需要击杀突变末影人，在它死后，会有末影残片出现\n这时你需要对准那些残片右键以驯服它们，越多越好\n再之后，身边有驯服的末影残片时，丢出一个末影之眼，你即可获得末影之手").yellow())
    event.add("l2complements:eternium_ingot", Text.of("请直接查看永恒块的合成配方").yellow())
    event.add("infinite_abyss:light_blue_crystal", Text.of("在第六层中可以挖掘得到").yellow())
    event.add("iceandfire:dread_shard", Text.of("击杀惊悚类别的生物可以获得").yellow())
    event.add("cataclysm:void_core", Text.of("由末影傀儡掉落\n末影傀儡沉睡在废弃堡垒的第一、二层\n废弃堡垒是一个生成于末地外岛的建筑").yellow())
    event.add("cataclysm:crystallized_coral_fragments", Text.of("击杀珊瑚傀儡可以掉落").yellow())
    event.add("aquamirae:ship_graveyard_echo", Text.of("通过击杀冰雪迷阵内除金蛾和棘鱼的海灵物语生物概率掉落\n也可以通过打开冰冻箱子概率获得").yellow())
    event.add("aquamirae:anglers_fang", Text.of("击杀鮟鱇鱼小概率掉落，鮟鱇鱼刷怪蛋可以自行制作").yellow())
    event.add("aquamirae:abyssal_amethyst", Text.of("击杀迷阵之母可得到深海紫水晶，迷阵之母的刷怪蛋可以自行合成").yellow())
    event.add("divinerpg:arcanium_extractor", Text.of("在秘界的部分房间随机刷新\n其中在第九层，第十二层，第十四层获取的概率较大").yellow())
    event.add("savage_and_ravage:blast_proof_plating", Text.of("直接击杀苦力怕可掉落").yellow())
    event.add("enigmaticlegacy:etherium_ingot", Text.of("它的矿物可以被合成").yellow())
    event.add("aether:golden_amber", Text.of("挖掘金琥珀原木掉落").yellow())
    event.add("twilightforest:magic_beans", Text.of("在巨魔洞窟内的由普通黑曜石围成的宝箱中必定能够找到\n巨魔洞窟（Troll Caves）是生成于暮色高原的地下洞穴").yellow())
    event.add("iceandfire:hippocampus_fin", Text.of("杀死海马必定掉落").yellow())
    event.add("l2complements:sun_membrane", Text.of("也可以自行合成").yellow())
    event.add("divinerpg:aquamarine", Text.of("通过收获成熟的海蓝球作物获得\n海蓝宝石种子在秘界生成的交易npc朗姆处用4魔物交易获得").yellow())
    event.add("divinerpg:halite_helmet", Text.of("暮光恶魔50%掉落").yellow())
    event.add("divinerpg:halite_boots", Text.of("暮光恶魔50%掉落").yellow())
    event.add("divinerpg:halite_leggings", Text.of("雷沃尔掉落一个").yellow())
    event.add("divinerpg:halite_chestplate", Text.of("颠索斯掉落一个").yellow())
    event.add("infinite_abyss:glow_bulb", Text.of("在第四层中可以采摘得到").yellow())
    event.add("infinite_abyss:mycelium_vine", Text.of("在第四层的天花板中可以采摘得到").yellow())
    event.add("infinite_abyss:large_brown_mushroom", Text.of("在第四层中可以采摘得到").yellow())
    event.add("infinite_abyss:puffball_block", Text.of("一般在第四层的水底出现").yellow())
    event.add("infinite_abyss:flawless_light_blue_crystal", Text.of("淡蓝色水晶块可在第六层中找到，它可以分解为粗淡蓝色水晶").yellow())
    event.add("infinite_abyss:ice_rock", Text.of("可以在第六层中找到").yellow())
    event.add("infinite_abyss:ice_spike", Text.of("可以在第六层中找到").yellow())
    event.add("infinite_abyss:icicle_bottom", Text.of("可以在第六层中找到").yellow())
    event.add("iceandfire:stymphalian_bird_feather", Text.of("铜羽泽鹗向玩家射出的羽毛，过一段时间会掉落成为可拾取物品，也可以杀死铜羽泽鹗取得").yellow())
    event.add("deeperdarker:sculk_transmitter", Text.of("只能在幽匿维度中的远古神庙 (Sculk Transmitter)中找到").yellow())
    event.add("botania:black_lotus", Text.of("丢进有魔力的魔力池可以让魔力池获得更多魔力").yellow())
    event.add("createappliedkinetics:energy_provider", Text.of("对着能源接收器才可以放置").yellow())
    event.add("enigmaticlegacy:earth_heart", Text.of("做纯净之心或扭曲之心需要被轻微污染的大地之心\n需要在戴有七咒之戒的情况下，将大地之心放在背包内一下\n才能将大地之心转变为轻微污染").yellow())
    event.add("iter_rpg:blood_bottle", Text.of("主手拿放血者，副手拿玻璃瓶，击杀村民或动物即可获得").yellow())
    event.add("mowziesmobs:bluff_rod", Text.of("击杀泥峭人死亡掉落0~1个\n交给雕刻家—通臂大师来开启跑酷挑战！\n挑战通过即可获得大地手套").yellow())
    event.add("mowziesmobs:earthrend_gauntlet", Text.of("通过雕刻家—通臂大师的挑战即可获得").yellow())
    event.add("extrabotany:sanguine_pleiades_combat_maid_suit", Text.of("喝下装有猩红之血的小瓶后\n穿上昴宿星团战斗女仆服\n在嗜血效果结束前杀死50只怪物\n待效果自然结束后变为血染昴宿星团战斗女仆服").yellow())
    event.add("extrabotany:hero_medal", Text.of("打开潘多拉魔盒必定获得一个，潘多拉魔盒通过击败盖亚守护者III获得").yellow())
    event.add("mythicbotany:fimbultyr_tablet", Text.of("喝下装有密米尔之泉水的加拉尔号角后击杀盖亚守护者Ⅱ掉落").yellow())
    event.add("mythicbotany:gjallar_horn_full", Text.of("将【加拉尔号角】放在【世界树的枝干】上\n使用魔力发射器对【世界树的枝干】进行充能\n一段时间后即可获得装有密米尔之泉水的加拉尔号角").yellow())
    event.add("mowziesmobs:captured_grottol", Text.of("用精准采集的镐攻击岩壳居蟹掉落").yellow())
    event.add("extrabotany:spirit_fuel", Text.of("通过食用梦魇燃料获得").yellow())
    event.add("mowziesmobs:umvuthana_mask_fury", Text.of("可以放在工作台上试试").yellow())
    event.add("mowziesmobs:umvuthana_mask_fear", Text.of("可以放在工作台上试试").yellow())
    event.add("mowziesmobs:umvuthana_mask_rage", Text.of("可以放在工作台上试试").yellow())
    event.add("mowziesmobs:umvuthana_mask_bliss", Text.of("可以放在工作台上试试").yellow())
    event.add("mowziesmobs:umvuthana_mask_misery", Text.of("可以放在工作台上试试").yellow())
    event.add("mowziesmobs:umvuthana_mask_faith", Text.of("可以放在工作台上试试").yellow())
    event.add("mowziesmobs:sol_visage", Text.of("可以放在工作台上试试").yellow())
    event.add("linzhi:left", Text.of("在工作台界面上可以转换成任务书中线").red())
    event.add("linzhi:mid", Text.of("在工作台界面上可以转换成任务书右线"))
    event.add("linzhi:right", Text.of("在工作台界面上可以转换成任务书左线").blue())
})  


/*
ItemEvents.firstRightClicked(event =>{
    /**
     * @type {Internal.ServerPlayer}
     */
    //let serverplayer = event.player
    //let playeruuid = serverplayer.UUID
    //let item = serverplayer.handSlots
    //serverplayer.addItem("infinite_abyss:guardian_armor_boots")
    //event.item.damageValue = 1000
    //event.item.count = 20
    //event.player.sendSystemMessage(String(item))
//})

/*
ItemEvents.tooltip((event) =>{
    //添加一个最普通的文本，这个文本是在最下面进行显示的
    //event.add('diamond', "添加一个普通文本")
    //用数组添加文本，在游戏内数组的每个文本都独占一行
    event.add('diamond', [
    "你说你不想在这里",
    "我也不想在这里",
    "但是天黑地太快想走早就来不及",
    "哦！我爱你"])
    //当你需要拼接字符串时可以使用下面方法
    //event.add('diamond', Text.of("该物品现属于").append(Client.player.username))
    //当你需要改变文本颜色时,只需要在后面添加一个颜色参数就可以
    //event.add('diamond', Text.of("该物品现属于").append(Client.player.username).red())
})
*/

