
["Mob's Strength and Weakness"]
	#Up to how much more health can mobs have? (%)
	health_increase = 35
	#Up to how much less health can mobs have? (%)
	health_decrease = 25
	#Up to how much more damage can mobs deal? (%)
	damage_increase = 30
	#Up to how much less damage can mobs deal? (%)
	damage_decrease = 15
	#Up to how much faster can mobs be? (%)
	speed_increase = 15
	#Up to how much slower can mobs be? (%)
	speed_decrease = 10

