# Don't change this! Version used to track needed updates.
version = 0
turnOffPotionParticles = "PLAYER"
reduceAllChance = 0.502451
reduceDecreasedChance = 0.34558824
disableParticles = false
byTypeReductions = {  }