"Mob Griefing Off (default: false)" = false
"Quicksand Griefing Off (default: false)" = false
"Griefing Drops Blocks On (default: false)" = false
"Mutant Despawning On (default: false)" = false
"Mutants Explode Into Parts Off (default: false)" = false
"Mutant Parts Glow On (default: false)" = false
"Mutants Attack Players Off (default: false)" = false
"Friendly Fire On (default: false)" = false

